import React from 'react'

export default function BlogPost() {
    return (
        <section id="BlogPost">
        <div className="container bg-light " >
        <div className="text-lead text-start">
            <p className="title text-start text-bold display-4" >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, omnis!</p>
            <p className="text muted" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur voluptatum sapiente temporibus voluptatem laboriosam, nisi recusandae doloremque placeat repellendus eligendi, odio quia earum, impedit dolorem quas quidem excepturi blanditiis esse sunt quisquam? Adipisci suscipit rerum labore odit? Maxime sapiente eius, odio dolorum tempora laborum ipsum obcaecati. Hic reiciendis et numquam pariatur voluptatibus nisi sit ipsa unde dolores incidunt tempora veritatis quaerat non saepe ex tempore magnam maiores quidem, reprehenderit id? Odio, nobis rerum voluptatum hic nostrum accusamus velit. Obcaecati unde quas dicta, distinctio, ratione mollitia adipisci vel doloribus, quod reprehenderit quidem? Necessitatibus saepe ab molestias dignissimos, ullam dolores, iure dolorum qui exercitationem maiores quasi magnam sequi? Deserunt repudiandae, debitis unde tenetur architecto optio, earum provident minima animi repellendus aspernatur facere hic tempore consequuntur, sed rerum distinctio neque nostrum nesciunt consequatur quo! Esse exercitationem nobis assumenda nisi rem quo, sequi odio laborum tempore id incidunt at delectus magnam molestias dignissimos soluta corporis adipisci, consequatur cum unde recusandae quae dolorum perspiciatis consectetur? Repellat quasi minima nemo molestias voluptatum! Totam ab sit porro iste consectetur corrupti nobis est laudantium nam? Beatae suscipit blanditiis qui repellat laboriosam tempora, aliquid, enim reprehenderit omnis soluta quasi minima corporis eius nihil sed nulla doloremque animi sapiente quod!</p>
            <p className="text muted" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur voluptatum sapiente temporibus voluptatem laboriosam, nisi recusandae doloremque placeat repellendus eligendi, odio quia earum, impedit dolorem quas quidem excepturi blanditiis esse sunt quisquam? Adipisci suscipit rerum labore odit? Maxime sapiente eius, odio dolorum tempora laborum ipsum obcaecati. Hic reiciendis et numquam pariatur voluptatibus nisi sit ipsa unde dolores incidunt tempora veritatis quaerat non saepe ex tempore magnam maiores quidem, reprehenderit id? Odio, nobis rerum voluptatum hic nostrum accusamus velit. Obcaecati unde quas dicta, distinctio, ratione mollitia adipisci vel doloribus, quod reprehenderit quidem? Necessitatibus saepe ab molestias dignissimos, ullam dolores, iure dolorum qui exercitationem maiores quasi magnam sequi? Deserunt repudiandae, debitis unde tenetur architecto optio, earum provident minima animi repellendus aspernatur facere hic tempore consequuntur, sed rerum distinctio neque nostrum nesciunt consequatur quo! Esse exercitationem nobis assumenda nisi rem quo, sequi odio laborum tempore id incidunt at delectus magnam molestias dignissimos soluta corporis adipisci, consequatur cum unde recusandae quae dolorum perspiciatis consectetur? Repellat quasi minima nemo molestias voluptatum! Totam ab sit porro iste consectetur corrupti nobis est laudantium nam? Beatae suscipit blanditiis qui repellat laboriosam tempora, aliquid, enim reprehenderit omnis soluta quasi minima corporis eius nihil sed nulla doloremque animi sapiente quod!</p>
            <p className="text muted" >Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur voluptatum sapiente temporibus voluptatem laboriosam, nisi recusandae doloremque placeat repellendus eligendi, odio quia earum, impedit dolorem quas quidem excepturi blanditiis esse sunt quisquam? Adipisci suscipit rerum labore odit? Maxime sapiente eius, odio dolorum tempora laborum ipsum obcaecati. Hic reiciendis et numquam pariatur voluptatibus nisi sit ipsa unde dolores incidunt tempora veritatis quaerat non saepe ex tempore magnam maiores quidem, reprehenderit id? Odio, nobis rerum voluptatum hic nostrum accusamus velit. Obcaecati unde quas dicta, distinctio, ratione mollitia adipisci vel doloribus, quod reprehenderit quidem? Necessitatibus saepe ab molestias dignissimos, ullam dolores, iure dolorum qui exercitationem maiores quasi magnam sequi? Deserunt repudiandae, debitis unde tenetur architecto optio, earum provident minima animi repellendus aspernatur facere hic tempore consequuntur, sed rerum distinctio neque nostrum nesciunt consequatur quo! Esse exercitationem nobis assumenda nisi rem quo, sequi odio laborum tempore id incidunt at delectus magnam molestias dignissimos soluta corporis adipisci, consequatur cum unde recusandae quae dolorum perspiciatis consectetur? Repellat quasi minima nemo molestias voluptatum! Totam ab sit porro iste consectetur corrupti nobis est laudantium nam? Beatae suscipit blanditiis qui repellat laboriosam tempora, aliquid, enim reprehenderit omnis soluta quasi minima corporis eius nihil sed nulla doloremque animi sapiente quod!</p>
        </div>    
        </div>
        </section>
    )
}
